language: java
if: tag IS present OR NOT (branch == master)
# before_cache:
#   - export MAVEN_LOCAL_REPOSITORY=$(mvn -B help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)
# cache:
#   directories:
#     - $MAVEN_LOCAL_REPOSITORY
jdk:
  - openjdk8
script:
  - mvn clean package sonar:sonar dependency-check:check bundle:bundle -Dsonar.login=${SONAR_PROJECT_TOKEN}
before_deploy:
  - export BUNDLE_JAR=$(ls nexus*jar)
  - echo "deploying $BUNDLE_JAR to GitHub releases"
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file_glob: true
  file:
    - "${BUNDLE_JAR}"
    - "target/site/jacoco/*"
    - "target/dependency-check-report.html"
  skip_cleanup: true
  on:
    tags: true