language: java
jdk:
  - openjdk8
before_deploy:
  - export BUNDLE_JAR=$(ls nexus*jar)
  - echo "deploying $BUNDLE_JAR to GitHub releases"
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "${BUNDLE_JAR}"
  skip_cleanup: true
  on:
    tags: true