language: java
if: tag IS present OR NOT (branch == master)
# before_cache:
#   - export MAVEN_LOCAL_REPOSITORY=$(mvn -B help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)
# cache:
#   directories:
#     - $MAVEN_LOCAL_REPOSITORY
install: mvn dependency:resolve
jdk:
  - openjdk8
before_script:
  - |
    if ["$TRAVIS_BRANCH" == "master" || "${TRAVIS_TAG}X" != "X"]; then
      mvn -q versions:set@remove-snapshot versions:commit@remove-snapshot -B;
    fi
script:
  - mvn clean package sonar:sonar dependency-check:check bundle:bundle -Dsonar.login=${SONAR_PROJECT_TOKEN} -B
before_deploy:
  - export BUNDLE_JAR=$(ls nexus*jar)
  - echo "deploying $BUNDLE_JAR to GitHub releases"
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file_glob: true
  file:
    - "${BUNDLE_JAR}"
    - "target/site/jacoco/*"
    - "target/dependency-check-report.html"
  skip_cleanup: true
  on:
    tags: true
after_success:
  - |
    if ["$TRAVIS_BRANCH" == "master" || "${TRAVIS_TAG}X" != "X"]; then
      mvn -q versions:set@rev-to-next-snapshot versions:commit@rev-to-next-snapshot -B
      git config --global user.name "Travis CI"
      git config --global user.email "travis@travisci.org"
      git remote add pushorigin https://${GITHUB_OAUTH_TOKEN}@github.com/InfoSec812/nexus-kubernetes-openshift.git
      git push pushorigin master
    fi
