language: java
if: tag IS present
# before_cache:
#   - export MAVEN_LOCAL_REPOSITORY=$(mvn -B help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)
# cache:
#   directories:
#     - $MAVEN_LOCAL_REPOSITORY
addons:
  sonarcloud:
    organization: "infosec812-github" # the key of the org you chose at step #3
    token:
      secure: "nYAQ+OBoCUDGWtne2Jn4s75S1jS4sPf1HNuLOdoLqhB2+QgcaQEelXIzmjefanyxG5Wjeyxyoblgn9ZU70Qtes9JUr0qG7NvI3Os3D688Q/7Y7K071m2A/kqYO7OVjHrc3NTvEK+MnP4HIUfgum9+VoQ6ZUGJHQ8fEapxuv11cZ0R6BeI4sn2dsSE3OKPjGxE6qBRni1HMPwiwLsTBaBWCwvRQKtC1FoeIacDJ3DH8NtF/vq83fWVEhyKNxpbXUJSRkkk/3G9fccaxBHddIzsuglJYOpfvgk1jOlldQlUpPrYYo6eRb1kI1ieX89vjvr2ugfA+kulysM4wtFBVEkt2bNxb85g8F3I/WG+FMqbNu2caLQ5/OjhEGuCb+zfyFJ8t4eLC98rBLgc0xTS9APy2EE7+3+mAT7uZJ525DoUYYi8dv1Th+gNk4eepg9X5gTKtILeGDoDZ3/us9P4I3sdszRPcdRYraZVrwLNLMzs4rT5YtNw9FZEHpsxrXXtyrYFec4i/GjKlY9CLlH08Byovtgxv1ch8d2KTQgMtWeKC3R2Qq+NbYzoMxH1lm3HdT6BsUJbql/nYwnZoKUNAdypOwvkboXwgIxK0/k6+dArnbosLTAjjEAIv0FpSxXEsuCN6ng/Vd4G+3XiF2CUPx3k8VdmKSNr9i83XoHg2dXT3s="
jdk:
  - openjdk8
script:
  - mvn clean package sonar:sonar dependency-check:check bundle:bundle
before_deploy:
  - export BUNDLE_JAR=$(ls nexus*jar)
  - echo "deploying $BUNDLE_JAR to GitHub releases"
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "${BUNDLE_JAR}"
  skip_cleanup: true
  on:
    tags: true