language: java
if: tag IS present OR NOT (branch == master)
# before_cache:
#   - export MAVEN_LOCAL_REPOSITORY=$(mvn -B help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)
# cache:
#   directories:
#     - $MAVEN_LOCAL_REPOSITORY
jdk:
  - openjdk8
stages:
  - name: before_script
    if: tag IS present OR NOT (branch == master)
  - name: script
  - name: before_deploy
    if: tag IS present OR NOT (branch == master)
  - name: deploy
    if: tag IS present OR NOT (branch == master)
  - name: after_success
    if: tag IS present OR NOT (branch == master)
before_script:
  - mvn versions:set@remove-snapshot versions:commit@remove-snapshot
script:
  - mvn clean package sonar:sonar dependency-check:check bundle:bundle -Dsonar.login=${SONAR_PROJECT_TOKEN}
before_deploy:
  - export BUNDLE_JAR=$(ls nexus*jar)
  - echo "deploying $BUNDLE_JAR to GitHub releases"
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file_glob: true
  file:
    - "${BUNDLE_JAR}"
    - "target/site/jacoco/*"
    - "target/dependency-check-report.html"
  skip_cleanup: true
  on:
    tags: true
after_success:
  - mvn versions:set@rev-to-next-snapshot versions:commit@rev-to-next-snapshot
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travisci.org"
  - git remote add pushorigin https://${GITHUB_OAUTH_TOKEN}@github.com/InfoSec812/nexus-kubernetes-openshift.git
  - git push pushorigin master
