language: java
if: tag IS present
before_cache:
  - export MAVEN_LOCAL_REPOSITORY=$(mvn -B help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)
cache:
  directories:
    - $MAVEN_LOCAL_REPOSITORY
addons:
  sonarcloud:
    organization: "infosec812-github" # the key of the org you chose at step #3
    token: "${SONAR_CLOUD_TOKEN}"
jdk:
  - openjdk8
script:
  - mvn clean package dependency-check:check bundle:bundle
  - sonar-scanner -Dsonar.projectKey="com.redhat.labs.nexus:nexus-openshift-plugin"
before_deploy:
  - export BUNDLE_JAR=$(ls nexus*jar)
  - echo "deploying $BUNDLE_JAR to GitHub releases"
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "${BUNDLE_JAR}"
  skip_cleanup: true
  on:
    tags: true